
[project]
version = '0.0.0'
name = 'Solar'

requires-python = '>=3.10'

dependencies = [
    'freecad-stubs>=1.0.21' ,
    'pyside6>=6.9.2' ,
    'ladybug-radiance>=0.2.11' ,
    'ladybug-core>=0.44.29' ,
    'pysolar>=0.13'
]